server:
  port: 8080
  undertow:
    accesslog:
      dir: ./
      prefix: access_log
      rotate: true
spring:
  profiles:
    active: prod
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mspos_db?useUnicode=true&characterEncoding=UTF8&connectTimeout=10000&socketTimeout=100000&allowMultiQueries=true&useSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:sql/schema.sql
    initialization-mode: always
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.**.bean
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.**.bean
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker_str
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false